### ISSUE TITLE
Handling `xorg-x11-server-Xvfb`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/nionui-tool-feedstock#51]
Noticed the recipe has the following test commented and includes a `yum install`

https://github.com/conda-forge/nionui-tool-feedstock/blob/9483115ddc98f480a54552b49ad7ca767c32eb88/recipe/meta.yaml#L78-L80

To fix this test and handle the `xorg-x11-server-Xvfb` dependency properly would suggest adding...

...[the CDT]( https://conda-forge.org/docs/glossary/#cdt ) to `recipe/meta.yaml`...

```yaml
requirements:
  build:
    ...
    - {{ cdt('xorg-x11-server-xvfb') }}     # [linux]
    ...
```

...and this to [`recipe/yum_requirements.txt`]( https://conda-forge.org/docs/maintainer/knowledge_base/#yum_requirementstxt )...

```
xorg-x11-server-Xvfb
```

...then [re-rendering]( https://conda-forge.org/docs/maintainer/updating_pkgs/#rerendering-feedstocks )
